### ISSUE TITLE
Models' breakdown

### ISSUE THREAD

**Issue by matfire** [zero-to-mastery/project_paycheck#50]
I've written down what I think could be a good starting point for the different models needed. All that is not covered as a model could be easily extrapolated with some calculations, if I'm not mistaken. Perhaps a separate Paycheck model would be best?

[you can find it here](https://dbdiagram.io/d/5d651549ced98361d6ddf464)

**Comment by notAnkur** [comment]
Lets go with separate user and paycheck model.

**Comment by matfire** [comment]
So something more like [this](https://dbdiagram.io/d/5d651549ced98361d6ddf464)

**Comment by notAnkur** [comment]
sure
